apps/file/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    (r'^index.we$', views.index),
    url(r'^(?P<pk>[\w\-]+).we$', views.FileView.as_view(), name='detail'),
    url(r'^(?P<id>[\w\-]+)/download.we$', views.download, name='download'),
    url(r'^(?P<pk>[\w\-]+)/play.we$', views.PlayView.as_view(), name='play'),
)

apps/iptv/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    (r'^index.we$', views.index),
    url(r'^tv.we$', views.tv, name='tv'),
    url(r'^voice_of_china_2014.we$', views.voice_of_china_2014, name='voice_of_china_2014'),
    url(r'^worldcup_2014.we$', views.worldcup_2014, name='worldcup_2014'),
)

we/urls.py
from django.conf.urls import patterns, include

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'we.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    (r'^([^/]+/)?common/', include('common.urls')),
    (r'^www/', include('apps.www.urls', namespace='www')),
    (r'^mirror/', include('apps.mirror.urls', namespace='mirror')),
    (r'^genuine/', include('apps.genuine.urls', namespace='genuine')),
    (r'^file/', include('apps.file.urls', namespace='file')),
    (r'^iptv/', include('apps.iptv.urls', namespace='iptv')),
    (r'^open/', include('apps.open.urls', namespace='open')),

    (r'^me/', include('apps.me.urls', namespace='me')),

    (r'^admin/', include(admin.site.urls)),
)

apps/iptv/models.py
#coding=utf8
from django.db import models

from django_uuid_pk.fields import UUIDField

class Group(models.Model):
    name = models.CharField(u'频道组', max_length=32)
    order = models.IntegerField(u'排序')

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['order']
        verbose_name = u'频道组'
        verbose_name_plural = u'频道组'

class Channel(models.Model):
    group = models.ForeignKey(Group, verbose_name=u'频道组')
    name = models.CharField(u'频道名', max_length=32)
    channel = models.CharField(u'频道号', max_length=32)
    order = models.IntegerField(u'排序')

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['group', 'order']
        verbose_name = u'频道'
        verbose_name_plural = u'频道'

class Point(models.Model):
    id = UUIDField(primary_key=True)
    channel = models.ForeignKey(Channel, verbose_name=u'频道')
    source = models.CharField(u'源名称', max_length=32)
    target = models.CharField(u'目标名', max_length=32)
    hd = models.BooleanField(u'高清', default=False)
    sound = models.IntegerField(u'声道数')
    active = models.BooleanField(u'活动', default=False)

    def __unicode__(self):
        return self.channel.name

    class Meta:
        ordering = ['channel', '-hd']
        verbose_name = u'频道点'
        verbose_name_plural = u'频道点'

class Guide(models.Model):
    channel = models.ForeignKey(Channel, verbose_name=u'频道')
    time = models.TimeField(u'时间')
    name = models.CharField(u'节目', max_length=64)

    def __unicode__(self):
        return self.channel.name + ' (' + str(self.time) + ')'

    class Meta:
        ordering = ['channel', 'time']
        verbose_name = u'节目'
        verbose_name_plural = u'节目'

apps/iptv/views.py
from django.shortcuts import render_to_response, get_object_or_404

from .models import Group, Channel, Guide

from datetime import datetime, time
from os.path import isfile
import csv
import json

from navigation import get_navbar

def index(request):
    result = get_navbar(request)
    get_active_channel(result)

    return render_to_response('iptv/index.html', result)

def tv(request):
    result = get_navbar(request)
    get_active_channel(result)

    channel = get_object_or_404(Channel, channel=request.GET.get('channel', 'CCTV-1'))
    for group in result['channels']:
        for item in group['channels']:
            if item['channel'] == channel.channel:
                group.update({'active': True})
                result.update({'channel': item})
                break

    guide = Guide.objects.filter(channel=channel)

    noon = time(12)
    am = guide.filter(time__lt=noon)
    pm = guide.filter(time__gte=noon)
    result.update({'items': {'am': am, 'pm': pm}})

    now = datetime.now().time()
    index = guide.filter(time__lt=now).count() - 1
    if index < len(am):
        result.update({'current': {'am': index}})
    else:
        result.update({'current': {'pm': index - len(am)}})

    return render_to_response('iptv/tv.html', result)

def get_active_channel(result):
    groups = Group.objects.all()

    data = []
    for group in groups:
        channels = []
        for channel in group.channel_set.all():
            points = []
            for point in channel.point_set.filter(active=True):
                points.append(point)
            if points:
                channels.append({'name': channel.name, 'channel': channel.channel, 'point': points, 'hd': points[0].hd})
        if channels:
            data.append({'name': group.name, 'channels': channels})

    result.update({'channels': data})

def voice_of_china_2014(request):
    result = get_navbar(request)

    return render_to_response('iptv/voice_of_china_2014.html', result)

def worldcup_2014(request):
    result = get_navbar(request)

    return render_to_response('iptv/worldcup_2014.html', result)

apps/iptv/templates/iptv/index.html
{% extends "we/hero.html" %}
{% load staticfiles %}

{% block title %}网络电视{% endblock %}

{% block hero_title %}We - 网络电视{% endblock %}
{% block hero_subtitle %}校园网络电视现在开播！{% endblock %}

{% block content %}
  <div class="container">
    <p class="alert alert-warning"><strong>免责声明：</strong>We 没有在任何其他位置发布链接到网络电视的脚本、软件及页面，本页面为惟一发布方式。如使用第三方方式导致的不良后果，We 不承担任何责任。
    <section>
      <header class="page-header">
        <h3>说明</h3>
      </header>
      <p>本站所有频道均为北京邮电大学采集的歌华有线和东北大学采集的地面数字电视信号，并由东北大学传送至 We 。目前 We 完整转播了全部 86 套节目，其中高清频道 24 套，标清频道 62 套。
      <p>现在本系统为试运行阶段，期间所有频道均可免费自由观看。
    </section>
    <section>
      <header class="page-header">
        <h3>频道列表</h3>
      </header>
      <ul>
  {% for group in channels %}
        <li>
          <strong>{{ group.name }}：</strong>
    {% for channel in group.channels %}
          <a href="{% url 'iptv:tv' %}?channel={{ channel.channel|urlencode }}">{% if channel.point.0.hd %}<span class="glyphicon glyphicon-hd-video"></span>{% endif %}{% if channel.point.0.sound == 6 %}<span class="glyphicon glyphicon-sound-5-1"></span>{% endif %}{{ channel.name }}</a>{% if not forloop.last %}、{% endif %}
    {% endfor %}
  {% endfor %}
      </ul>
    </section>
    <section>
      <header class="page-header">
        <h3>往期节目</h3>
      </header>
      <ul>
        <li>
          <strong>2014/15赛季欧冠决赛：</strong><a href="{% url 'file:detail' 'DSPteB_DS1Kd7buNokQAaw' %}">H.264</a>、<a href="{% url 'file:detail' 'Jt8mXiOVTE-x83R2LqktuA' %}">H.265</a>
        <li>
          <a href="{% url 'iptv:voice_of_china_2014' %}">2014 中国好声音</a>
        <li>
          <a href="{% url 'iptv:worldcup_2014' %}">2014 巴西世界杯</a>
      </ul>
    </section>
    <section>
      <header class="page-header">
        <h3>常见问题</h3>
      </header>
      <ol>
        <li>
          <p><strong>哪些播放器可以播放？</strong>
          <p>目前 PC 上经过测试的只有 VLC 播放器，iOS 系统及部分 android 系统可直接播放。
        <li>
          <p><strong>为什么点击在线播放按钮后没有播放？</strong>
          <p>由于 PC 上的 VLC 播放器没有通过浏览器插件及后台服务等手段对浏览器和剪贴版进行监视，因此需要手动进行以下操作方可播放：
          <ol>
            <li>在页面中的频道按钮上右击选择<strong>「复制链接地址」</strong>一类的选项；
            <li>打开 VLC 播放器，按键盘组合键<code>ctrl</code>+<code>N</code>；
            <li>在弹出的窗口中粘贴后点击<strong>「播放」</strong>按钮即可观看。
          </ol>
        <li>
          <p><strong>为什么有时播放节目会卡顿或无法播放？</strong>
          <p>由于节目是由北京邮电大学实时采集，又经由东北大学转发，其中任何环境出现问题都会造成节目信号卡顿甚至中断，出现此类问题只需等待一段时间或直接与 We 联系即可。
        <li>
          <p><strong>喜欢看一档节目，可以帮助录制吗？</strong>
          <p>可以的，请尽早与 We 联系，以方便安排录制计划。在不与其他录制计划冲突并且信号稳定的前提下，我们将尽力完整录制。
      </ol>
    </section>
  </div>
{% endblock %}

apps/iptv/templates/iptv/tv.html
{% extends "we/base.html" %}
{% load staticfiles %}

{% block title %}网络电视{% endblock %}

{% block extra_css %}
  <link href="{% static 'iptv/css/we-iptv.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
  <div class="container">
    <section>
      <div id="channels" class="panel-group col-md-3">
  {% for group in channels %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title"><a data-toggle="collapse" data-parent="#channels" href="#group{{ forloop.counter0 }}">{{ group.name }}</a></h4>
          </div>
          <div id="group{{ forloop.counter0 }}" class="panel-collapse collapse{% if group.active %} in{% endif %}">
            <div class="panel-body">
    {% for channel in group.channels %}
              <a href="?channel={{ channel.channel|urlencode }}"><i class="glyphicon glyphicon-chevron-right"></i>{{ channel.name }}</a><br>
    {% endfor %}
            </div>
          </div>
        </div>
  {% endfor %}
      </div>
      <div class="col-md-9">
        <header class="page-header">
          <h1>
            {{ channel.name }}
  {% for point in channel.point %}
            <a id="play" href="/iptv/iptv/{{ point.source }}.m3u8" class="btn btn-primary"><span class="glyphicon glyphicon-{% if point.hd %}hd{% else %}sd{% endif %}-video"></span>{% if point.sound > 1 %}<span class="glyphicon glyphicon-sound-{% if point.sound == 2 %}stereo{% elif point.sound == 6 %}5-1{% endif %}"></span>{% endif %} {% if point.hd %}高清频道{% else %}标清频道{% endif %}</a>
  {% endfor %}
          </h1>
        </header>
        <div class="row">
          <div class="col-md-6">
  {% if items.am or items.pm %}
    {% if current.am < 0 and current.pm < 0 %}
            <p><img src="/iptv/screenshot/{{ channel.point.0.target }}.png">
    {% endif %}
    {% for item in items.am %}
      {% if forloop.counter0 == current.am %}
            <p><strong>{{ item.time|date:'H:i' }}&nbsp;&nbsp;{{ item.name }}</strong>
            <p><img src="/iptv/screenshot/{{ channel.point.0.target }}.png">
      {% else %}
            <p{% if forloop.counter0 < current.am or current.pm %} class="text-muted"{% endif %}>{{ item.time|date:'H:i' }}&nbsp;&nbsp;{{ item.name }}
      {% endif %}
    {% endfor %}
          </div>
          <div class="col-md-6">
    {% for item in items.pm %}
      {% if forloop.counter0 == current.pm %}
            <p><strong>{{ item.time|date:'H:i' }}&nbsp;&nbsp;{{ item.name }}</strong>
            <p><img src="/iptv/screenshot/{{ channel.point.0.target }}.png">
      {% else %}
            <p{% if forloop.counter0 < current.pm %} class="text-muted"{% endif %}>{{ item.time|date:'H:i' }}&nbsp;&nbsp;{{ item.name }}
      {% endif %}
    {% endfor %}
  {% else %}
            <p><img src="/iptv/screenshot/{{ channel.point.0.target }}.png">
  {% endif %}
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}

apps/iptv/templates/iptv/voice_of_china.html
{% extends "we/base.html" %}
{% load staticfiles %}

{% block title %}中国好声音专版 - 网络电视{% endblock %}

{% block extra_css %}
  <link href="{% static 'iptv/css/we-iptv.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="{% url 'iptv:index' %}">网络电视</a>
      <li class="active">中国好声音专版
    </ol>
    <p class="alert alert-warning"><strong>版权声明：</strong>本页面所有录像版权归浙江卫视所有，仅供个人学习研究使用，请于下载后 24 小时内删除。不得用于商业用途，不得进行任何形式的复制、剪辑、转码、发布，如需获得使用权利，请与浙江卫视联系。
    <section>
      <header class="page-header">
        <h3>直播频道</h3>
      </header>
      <div class="channel">
        <dl>
          <dt><img src="http://iptv.neusoft.edu.cn/screenshots/zhejiang.png"></dt>
          <dd>
            <a href="mms://mms.we.neusoft.edu.cn/zhejiang" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-play"></span> 浙江卫视 高清</a>
          </dd>
        </dl>
        <dl>
          <dt><img src="http://iptv.neusoft.edu.cn/screenshots/zhejiang-SD.png"></dt>
          <dd>
            <a href="mms://mms.we.neusoft.edu.cn/zhejiang-SD" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-play"></span> 浙江卫视 标清</a>
          </dd>
        </dl>
      </div>
      <div class="clearfix"></div>
    </section>
    <section>
      <header class="page-header">
        <h3>录像下载及回放</h3>
      </header>
      <div>
{% for item in items %}
  {% if forloop.counter <= 6 %}
    {% if forloop.counter == 1 %}
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th colspan="3">盲选赛
          <tbody>
    {% endif %}
    {% if forloop.counter0|divisibleby:"3" %}
            <tr{% cycle '' ' class="active"' %}>
    {% endif %}
  {% elif forloop.counter <= 10 %}
    {% if forloop.counter == 7 %}
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th colspan="2">组内淘汰赛
          <tbody>
    {% endif %}
    {% if forloop.counter0|divisibleby:"2" %}
            <tr{% cycle '' ' class="active"' %}>
    {% endif %}
  {% elif forloop.counter <= 12 %}
    {% if forloop.counter == 11 %}
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th colspan="2">终极考核
          <tbody>
    {% endif %}
    {% if forloop.counter0|divisibleby:"2" %}
            <tr{% cycle '' ' class="active"' %}>
    {% endif %}
  {% elif forloop.counter <= 13 %}
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th>巅峰对战总决赛
          <tbody>
            <tr>
  {% endif %}
              <td>
  {% if item.id %}
                <a href="{% url 'file:detail' item.id %}">{{ item.name }}</a>
  {% else %}
                {{ item.name }}
  {% endif %}
  {% if forloop.counter == 6 or forloop.counter == 10 or forloop.counter == 12 or forloop.last %}
        </table>
  {% endif %}
{% endfor %}
      </div>
    </section>
  </div>
{% endblock %}

apps/iptv/templates/iptv/voice_of_china_2014.html
{% extends "we/base.html" %}
{% load staticfiles %}

{% block title %}2014 中国好声音 - 网络电视{% endblock %}

{% block extra_css %}
  <link href="{% static 'iptv/css/we-iptv.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="{% url 'iptv:index' %}">网络电视</a>
      <li class="active">2014 中国好声音
    </ol>
    <p class="alert alert-warning"><strong>版权声明：</strong>本页面所有录像版权归浙江卫视所有，不得用于商业用途，不得进行任何形式的复制、剪辑、转码、发布，如需获得使用权利，请与浙江卫视联系。
    <section>
      <div>
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th colspan="3">盲选赛
          <tbody>
            <tr>
              <td>
                <a href="{% url 'file:detail' 'N0PcsbnTQiaQMbmbdnqQJg' %}">第一期 (7/18)</a>
              <td>
                <a href="{% url 'file:detail' 'S7meJFJSRZKRew3yFwjnSA' %}">第三期 (8/1)</a>
              <td>
                <a href="{% url 'file:detail' 'ouN3O2reRCuDjfWwCZkNHw' %}">第五期 (8/15)</a>
            <tr class="active">
              <td>
                <a href="{% url 'file:detail' 'XWy5sTDEQ6aci3Gwv-triQ' %}">第二期 (7/25)</a>
              <td>
                <a href="{% url 'file:detail' 'II0JWkBoSVWI1AwR768IXg' %}">第四期 (8/8)</a>
              <td>
                <a href="{% url 'file:detail' '8xJwQuCRRYu0-7kq8M7q5g' %}">第六期 (8/22)</a>
        </table>
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th colspan="2">组内淘汰赛
          <tbody>
            <tr>
              <td>
                <a href="{% url 'file:detail' 'wWdM-ZZ-SjWwkWXNU1I-Yg' %}">那英 导师战队 (8/29)</a>
              <td>
                <a href="{% url 'file:detail' 'zE7EveRGRYO9duI4uHVvfg' %}">杨坤 导师战队 (9/12)</a>
            <tr class="active">
              <td>
                <a href="{% url 'file:detail' 'GX-sM3t6T3mgTJ_xvR2xgA' %}">汪峰 导师战队 (9/5)</a>
              <td>
                <a href="{% url 'file:detail' 'W9gc3SmHRYWBTMxGycd7-g' %}">齐秦 导师战队 (9/19)</a>
        </table>
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th colspan="2">终极考核
          <tbody>
            <tr>
              <td>
                <a href="{% url 'file:detail' 'tBj54KhGTBShg5wevdlLHQ' %}">那英/杨坤 导师战队 (9/26)</a>
              <td>
                <a href="{% url 'file:detail' 'GGxoXILOTxCnWYoHJ5DDpw' %}">齐秦/汪峰 导师战队 (9/30)</a>
        </table>
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th>巅峰对战总决赛
          <tbody>
            <tr>
              <td>
                <a href="{% url 'file:detail' 'QuNwlvF1SE-m2K7x_KxaLw' %}">总决赛 (10/7)</a>
        </table>
      </div>
    </section>
  </div>
{% endblock %}

apps/iptv/templates/iptv/worldcup.html
{% extends "we/base.html" %}
{% load staticfiles %}

{% block title %}世界杯专版 - 网络电视{% endblock %}

{% block extra_css %}
  <link href="{% static 'iptv/css/we-iptv.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="{% url 'iptv:index' %}">网络电视</a>
      <li class="active">世界杯专版
    </ol>
    <p class="alert alert-warning"><strong>版权声明：</strong>本页面所有录像版权归中央电视台所有，仅供个人学习研究使用，请于下载后 24 小时内删除。不得用于商业用途，不得进行任何形式的复制、剪辑、转码、发布，如需获得使用权利，请与中央电视台联系。
    <section>
      <header class="page-header">
        <h3>直播频道</h3>
      </header>
      <div class="channel">
        <dl>
          <dt><img src="http://drop.we.neusoft.edu.cn/CCTV-5-HD.png"></dt>
          <dd>
            <a href="mms://mms.we.neusoft.edu.cn/CCTV-5" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-play"></span> CCTV-5 高清</a>
          </dd>
        </dl>
        <dl>
          <dt><img src="http://drop.we.neusoft.edu.cn/hdtest.png"></dt>
          <dd>
            <a href="mms://mms.we.neusoft.edu.cn/CCTV-5-HD" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-play"></span> CCTV-5 准高清</a>
          </dd>
        </dl>
        <dl>
          <dt><img src="http://drop.we.neusoft.edu.cn/cctv5.png"></dt>
          <dd>
            <a href="mms://mms.we.neusoft.edu.cn/CCTV-5-SD" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-play"></span> CCTV-5 标清</a>
          </dd>
        </dl>
        <dl>
          <dt><img src="http://drop.we.neusoft.edu.cn/CCTV-5plus-HD.png"></dt>
          <dd>
            <a href="mms://mms.we.neusoft.edu.cn/CCTV-5+" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-play"></span> CCTV-5+ 高清</a>
          </dd>
        </dl>
        <dl>
          <dt><img src="http://drop.we.neusoft.edu.cn/CCTV-1-HD.png"></dt>
          <dd>
            <a href="mms://mms.we.neusoft.edu.cn/CCTV-1" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-play"></span> CCTV-1 高清</a>
          </dd>
        </dl>
      </div>
      <div class="clearfix"></div>
      <header class="page-header">
        <h3>录像下载及回放</h3>
      </header>
      <div>
{% for item in items %}
  {% if forloop.counter0 <= 0 %}
    {% if forloop.counter0 == 0 %}
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th>开幕式
          <tbody>
    {% endif %}
            <tr>
              <td>
  {% elif forloop.counter0 <= 48 %}
    {% if forloop.counter0 == 1 %}
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th colspan="4">小组赛
          <tbody>
    {% endif %}
    {% if forloop.counter0|add:"5"|divisibleby:"6" %}
            <tr{% cycle '' ' class="active"' %}>
              <td rowspan="2">{% cycle 'A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' %} 组
              <td>
    {% elif forloop.counter0|add:"5"|divisibleby:"3" %}
            <tr{% cycle '' ' class="active"' %}>
              <td>
    {% else %}
              <td>
    {% endif %}
  {% elif forloop.counter0 <= 56 %}
    {% if forloop.counter0 == 49 %}
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th colspan="4">1/8 决赛
          <tbody>
    {% endif %}
    {% if forloop.counter0|add:"3"|divisibleby:"4" %}
            <tr{% cycle '' ' class="active"' %}>
              <td>
    {% else %}
              <td>
    {% endif %}
  {% elif forloop.counter0 <= 60 %}
    {% if forloop.counter0 == 57 %}
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th colspan="2">1/4 决赛
          <tbody>
    {% endif %}
    {% if forloop.counter0|add:"1"|divisibleby:"2" %}
            <tr{% cycle '' ' class="active"' %}>
              <td>
    {% else %}
              <td>
    {% endif %}
  {% elif forloop.counter0 <= 62 %}
    {% if forloop.counter0 == 61 %}
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th colspan="2">半决赛
          <tbody>
    {% endif %}
    {% if forloop.counter0|add:"1"|divisibleby:"2" %}
            <tr>
              <td>
    {% else %}
              <td>
    {% endif %}
  {% elif forloop.counter0 <= 63 %}
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th>三四名决赛
          <tbody>
            <tr>
              <td>
  {% elif forloop.counter0 <= 64 %}
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th>决赛
          <tbody>
            <tr>
              <td>
  {% elif forloop.counter0 <= 65 %}
        <table class="table table-iptv table-condensed">
          <thead>
            <tr>
              <th>闭幕式
          <tbody>
            <tr>
              <td>
  {% endif %}
  {% if item.id %}
                <a href="{% url 'file:detail' item.id %}">{{ item.name }}</a>
  {% else %}
                {{ item.name }}
  {% endif %}
  {% if forloop.counter0 == 0 or forloop.counter0 == 48 or forloop.counter0 == 56 or forloop.counter0 == 60 or forloop.counter0 == 62 or forloop.counter0 == 63 or forloop.counter0 == 64 or forloop.last %}
        </table>
  {% endif %}
{% endfor %}
        <p class="alert alert-info"><strong>说明：</strong>(A1) 为 A 组第一名，(A1|B2) 为 A 组第一名或 B 组第二名，依上轮成绩而定。其余依次类推。
      </div>
    </section>
  </div>
{% endblock %}