apps/file/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    (r'^index.we$', views.index),
    url(r'^(?P<pk>[\w\-]+).we$', views.FileView.as_view(), name='detail'),
    url(r'^(?P<id>[\w\-]+)/download.we$', views.download, name='download'),
    url(r'^(?P<pk>[\w\-]+)/play.we$', views.PlayView.as_view(), name='play'),
)

we/urls.py
from django.conf.urls import patterns, include

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'we.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    (r'^([^/]+/)?common/', include('common.urls')),
    (r'^www/', include('apps.www.urls', namespace='www')),
    (r'^mirror/', include('apps.mirror.urls', namespace='mirror')),
    (r'^genuine/', include('apps.genuine.urls', namespace='genuine')),
    (r'^file/', include('apps.file.urls', namespace='file')),
    (r'^iptv/', include('apps.iptv.urls', namespace='iptv')),
    (r'^open/', include('apps.open.urls', namespace='open')),

    (r'^me/', include('apps.me.urls', namespace='me')),

    (r'^admin/', include(admin.site.urls)),
)

apps/file/models.py
#coding=utf-8
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from django_uuid_pk.fields import UUIDField

from converter import file_size

class File(models.Model):
    id = UUIDField(primary_key=True)
    name = models.CharField(u'文件名', max_length=128)
    extension = models.CharField(u'扩展名', max_length=16)
    size = models.BigIntegerField(u'大小', editable=False)
    type = models.TextField(u'属性', editable=False)
    mime = models.CharField(u'MIME类型', max_length=64, editable=False)
    crc32 = models.CharField(u'CRC32值', max_length=8, editable=False)
    md5sum = models.CharField(u'MD5值', max_length=22, editable=False)
    sha1sum = models.CharField(u'SHA1值', max_length=27, editable=False)
    created = models.DateTimeField(u'上传时间', auto_now_add=True, editable=False)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('file:detail', args=[urlsafe_base64_encode(self.id.bytes)])

    def size_unit(self):
        return file_size(self.size)

    def md5(self):
        return self.decode(self.md5sum)

    def sha1(self):
        return self.decode(self.sha1sum)

    def decode(self, encoded):
        return urlsafe_base64_decode(encoded).encode('hex')

    def download_times(self):
        return self.download_set.order_by('file', 'ip', 'time').distinct('file', 'ip', 'time').count()

    class Meta:
        index_together = [
            ['md5sum', 'sha1sum'],
        ]
        ordering = ['-created']
        verbose_name = u'文件'
        verbose_name_plural = u'文件'

class Download(models.Model):
    file = models.ForeignKey('File', verbose_name='文件', editable=False)
    ip = models.GenericIPAddressField(u'用户IP', editable=False)
    referer = models.URLField(u'访问来源', null=True, editable=False)
    time = models.DateTimeField(u'下载时间', editable=False)

    def __unicode__(self):
        return self.file.name

    class Meta:
        unique_together = [
            ['file', 'ip', 'time'],
        ]
        ordering = ['-time']
        verbose_name = u'下载记录'
        verbose_name_plural = u'下载记录'

apps/file/views.py
from django.conf import settings
from django.core.signing import TimestampSigner, BadSignature
from django.db import IntegrityError
from django.http import Http404, StreamingHttpResponse
from django.shortcuts import get_object_or_404, redirect, render_to_response
from django.utils.baseconv import base62
from django.utils.http import urlquote, urlsafe_base64_decode, urlsafe_base64_encode
from django.views import generic

from datetime import date, datetime, timedelta
from uuid import UUID
from zlib import crc32

from models import File, Download
from backdoors import backdoors
from ip import get_ip, get_geo, get_speed
from navigation import get_navbar
from converter import file_size

FILE_ROOT = settings.FILE_ROOT
signer = TimestampSigner()

def index(request):
    result = get_navbar(request)

    unique_files = File.objects.order_by('md5sum', 'sha1sum').distinct('md5sum', 'sha1sum')
    total_sizes = 0
    for unique_file in unique_files:
        total_sizes += unique_file.size

    result.update({
        'file': {
            'total': File.objects.count(),
            'unique': len(unique_files),
            'size': file_size(total_sizes),
        },
        'download': {
            'today': len(Download.objects.filter(time__gte=date.today())),
            'week': len(Download.objects.filter(time__gt=date.today() - timedelta(days=6))),
            'month': len(Download.objects.filter(time__gt=date.today() - timedelta(days=29))),
        },
        'date': {
            'week': date.today() - timedelta(days=6),
            'month': date.today() - timedelta(days=29),
        },
    })

    return render_to_response('file/index.html', result)

class FileView(generic.DetailView):
    model = File

    def get_object(self):
        try:
            id = UUID(bytes=urlsafe_base64_decode(self.kwargs[self.pk_url_kwarg]))
        except ValueError:
            raise Http404
        self.kwargs[self.pk_url_kwarg] = id

        return super(FileView, self).get_object()

    def get_context_data(self, **kwargs):
        context = super(FileView, self).get_context_data(**kwargs)
        context.update(get_navbar(self.request))
        context.update({'id': urlsafe_base64_encode(kwargs['object'].id.bytes)})
        context.update({'key': signer.sign(get_value(self.request, kwargs['object'].id)).replace(':', '')[-33:]})
        context.update({'ip': str(get_ip(self.request))})
        context.update({'geo': get_geo(self.request)[1]})
        context.update({'speed': get_speed(self.request)})

        mimetype = kwargs['object'].mime
        if mimetype == 'application/x-iso9660-image':
            mimeicon = 'cd'
        elif mimetype.startswith('video'):
            mimeicon = 'film'
        else:
            mimeicon = 'file'
        context.update({'mimeicon': mimeicon})

        return context

class PlayView(generic.DetailView):
    model = File
    template_name = 'file/file_play.html'

    def get_object(self):
        try:
            id = UUID(bytes=urlsafe_base64_decode(self.kwargs[self.pk_url_kwarg]))
        except ValueError:
            raise Http404
        self.kwargs[self.pk_url_kwarg] = id

        return super(PlayView, self).get_object()

    def get_context_data(self, **kwargs):
        context = super(PlayView, self).get_context_data(**kwargs)
        context.update(get_navbar(self.request))
        context.update({'path': kwargs['object'].crc32[-2:] + '/' + kwargs['object'].md5sum + kwargs['object'].sha1sum})
        return context

def download(request, id):
    key = request.GET.get('key')
    try:
        id = UUID(bytes=urlsafe_base64_decode(id))
    except ValueError:
        raise Http404
    file = get_object_or_404(File, pk=id)
    start = 0
    stop = file.size - 1

    time = None
    valid = False
    if key:
        time = datetime.fromtimestamp(base62.decode(key[:6]))
        try:
            signer.unsign('%s:%s:%s' % (get_value(request, id), key[:6], key[6:]))
            valid = True
        except BadSignature:
            pass

    if not valid:
        if backdoors.validate_referer(request) or backdoors.validate_ip(request):
            time = datetime.now().replace(minute=0, second=0, microsecond=0)
        else:
            return redirect(file)

    referer = request.META.get('HTTP_REFERER')

    range = request.META.get('HTTP_RANGE')
    if range:
        start, stop = range.strip('bytes=').split('-')
        if not stop:
            stop = file.size - 1
    else:
        try:
            file.download_set.create(ip=str(get_ip(request)), referer=referer, time=time)
        except IntegrityError:
            pass

    response = StreamingHttpResponse(download_generator(file, int(start), int(stop)), 'application/octet-stream', 200 if not range else 206)
    response['Content-Disposition'] = 'attachment; filename*=UTF-8\'\'' + urlquote(file.name)
    response['Content-Length'] = str(int(stop) - int(start) + 1)
    if range:
        response['Content-Range'] = 'bytes ' + str(start) + '-' + str(stop) + '/' + str(file.size)
    return response

def download_generator(file, start, stop):
    file_path = file.crc32[-2:] + '/' + file.md5sum + file.sha1sum

    with open(FILE_ROOT + file_path, 'rb') as f:
        f.seek(start)
        while True:
            buffer = f.read(65536)
            if buffer:
                yield buffer
            else:
                break

def get_value(request, id):
    return '%s|%s' % (urlsafe_base64_encode(id.bytes), str(get_ip(request)))

apps/file/templates/file/file_detail.html
{% extends "we/base.html" %}

{% block title %}下载 {{ file.name }}{% endblock %}

{% block content %}
  <div class="container">
    <div class="page-header">
      <h3>文件信息</h3>
    </div>
    <table class="table table-bordered">
      <tr>
        <td style="width: 10%;"><strong>文件名</strong>
        <td style="width: 40%;">{{ file.name }}
        <td style="width: 10%;"><strong>文件类型</strong>
        <td style="width: 40%;">{{ file.extension }}
      <tr>
        <td><strong>文件大小</strong>
        <td>{{ file.size_unit }}
        <td><strong>MIME信息</strong>
        <td><span class="glyphicon glyphicon-{{ mimeicon }}"></span>{{ file.mime }}
      <tr>
        <td><strong>文件属性</strong>
        <td colspan="3">{{ file.type }}
      <tr>
        <td><strong>上传日期</strong>
        <td>{{ file.created|date:'Y 年 n 月 j 日 H:i' }}
        <td><strong>CRC32</strong>
        <td>{{ file.crc32 }}
      <tr>
        <td rowspan="2"><strong>下载地址</strong>
        <td rowspan="2">
          <a href="{% url 'file:download' id %}?key={{ key }}" class="btn btn-primary"><span class="glyphicon glyphicon-download"></span> 从 We 下载（{{ file.download_times }} 次）</a>
{% comment %}
{% if file.mime == "video/mp4" %}
          <a href="{% url 'file:play' id %}" class="btn btn-primary"><span class="glyphicon glyphicon-play"></span> 从 We 在线播放</a>
{% endif %}
{% endcomment %}
        <td><strong>MD5</strong>
        <td>{{ file.md5 }}
      <tr>
        <td><strong>SHA1</strong>
        <td>{{ file.sha1 }}
    </table>
    <div class="page-header">
      <h3>下载说明</h3>
    </div>
    <ol>
      <li>本下载地址仅限<strong>当前 IP 地址（{{ ip }}）</strong>进行无限次数多线程及断点下载；
      <li>在<strong>{{ geo }}</strong>环境下载，最高可达到<strong> {{ speed.bitrate }}（约 {{ speed.byterate }}）</strong>下载速度。<a href="http://speedtest.neusoft.edu.cn/" target="_blank" class="btn btn-link btn-xs"><span class="glyphicon glyphicon-dashboard"></span> 点此测速</a>；
      <li>下载完成后，请计算文件 CRC32 、 MD5 及 SHA1 值确认文件完整性。
      <li><em>如何你使用带有<strong>镜像搜索</strong>功能的下载工具，请注意选择<strong>仅从原始地址下载</strong>选项，否则可能会降低下载体验。<br>只要下载方式正确，一定可以达到所在线路的最大速率。</em>
    </ol>
  </div>
{% endblock %}

apps/file/templates/file/file_play.html
{% extends "we/base.html" %}

{% block title %}播放 {{ file.name }}{% endblock %}

{% block more_css %}
  <link href="//lib.hub.neusoft.edu.cn/video-js/video-js.css" rel="stylesheet" />
{% endblock %}

{% block more_head %}
  <script src="//lib.hub.neusoft.edu.cn/video-js/video.js"></script>
  <script>
    videojs.options.flash.swf = "http://lib.hub.neusoft.edu.cn/video-js/video-js.swf";
  </script> 
{% endblock %}

{% block content %}
  <div class="container">
    <div class="page-header">
      <h3>正在播放：{{ file.name }} （上传于 {{ file.created|date:'Y 年 n 月 j 日 H:i' }}） <a href="download.we" class="btn btn-primary"><span class="glyphicon glyphicon-download-alt"></span> 下载</a></h3>
    </div>
    <video width="854" height="480" controls class="video-js vjs-default-skin vjs-big-play-centered" data-setup="{}">
      <source src="http://play.we.neusoft.edu.cn/{{ path }}" type="video/mp4">
    </video>
    <div>播放体验取决于连接速率、浏览器兼容性及显卡驱动程序设置等综合因素，如无法流畅播放，请先下载后再观看。</div>
  </div>
{% endblock %}

apps/file/templates/file/index.html
{% extends "we/hero.html" %}

{% block title %}云盘{% endblock %}

{% block hero_title %}We - 云盘{% endblock %}
{% block hero_subtitle %}体验校园网极速文件共享下载！{% endblock %}

{% block content %}
  <div class="container">
    <div class="row-fluid">
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">文件统计</h3>
          </div>
          <div class="panel-body">
            <strong>全部文件：</strong>{{ file.total }} 个<br>
            <strong>物理文件：</strong>{{ file.unique }} 个<br>
            <strong>占用空间：</strong>{{ file.size }}
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">下载统计</h3>
          </div>
          <div class="panel-body">
            <strong>日统计：</strong>{{ download.today }} 次<br>
            <strong>周统计：</strong>{{ download.week }} 次<br>
            <strong>月统计：</strong>{{ download.month }} 次
          </div>
        </div>
      </div>
    </div>
    <section>
      <header class="page-header">
        <h3>说明</h3>
      </header>
      <strong>文件统计：</strong>
      <ul>
	<li><strong>全部文件：</strong>云盘系统中记录的文件总数量；
	<li><strong>物理文件：</strong>云盘存储中存放的文件总数量（相同内容文件只存放一次）；
	<li><strong>占用空间：</strong>云盘存储中存放的文件总大小；
      </ul>
      <strong>下载统计：</strong>
      <ul>
	<li><strong>日统计：</strong>从今天 0 点到现在总下载次数；
	<li><strong>周统计：</strong>从 {{ date.week|date:'n 月 j 日' }}到现在总下载次数；
	<li><strong>月统计：</strong>从 {{ date.month|date:'n 月 j 日' }}到现在总下载次数；
      </ul>
    </section>
  </div>
{% endblock %}