apps/file/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    (r'^index.we$', views.index),
    url(r'^(?P<pk>[\w\-]+).we$', views.FileView.as_view(), name='detail'),
    url(r'^(?P<id>[\w\-]+)/download.we$', views.download, name='download'),
    url(r'^(?P<pk>[\w\-]+)/play.we$', views.PlayView.as_view(), name='play'),
)

apps/genuine/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    (r'^index.we$', views.index),
    url(r'^download.we$', views.download, name='download'),
    (r'^iuv.we$', views.iuv),
)

we/urls.py
from django.conf.urls import patterns, include

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'we.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    (r'^([^/]+/)?common/', include('common.urls')),
    (r'^www/', include('apps.www.urls', namespace='www')),
    (r'^mirror/', include('apps.mirror.urls', namespace='mirror')),
    (r'^genuine/', include('apps.genuine.urls', namespace='genuine')),
    (r'^file/', include('apps.file.urls', namespace='file')),
    (r'^iptv/', include('apps.iptv.urls', namespace='iptv')),
    (r'^open/', include('apps.open.urls', namespace='open')),

    (r'^me/', include('apps.me.urls', namespace='me')),

    (r'^admin/', include(admin.site.urls)),
)

apps/genuine/models.py
#coding=utf8
from django.db import models

from django_uuid_pk.fields import UUIDField

class Catalog(models.Model):
    id = UUIDField(primary_key=True)
    parent = models.ForeignKey('self', verbose_name=u'上级分类', null=True, blank=True)
    name = models.CharField(u'分类', max_length=32)
    order = models.IntegerField(u'排序')

    def __unicode__(self):
        if self.parent:
            return unicode(self.parent) + '/' + self.name
        else:
            return '/' + self.name

    class Meta:
        ordering = ['order']
        verbose_name = u'分类'
        verbose_name_plural = u'分类'

class Item(models.Model):
    parent = models.ForeignKey(Catalog, verbose_name=u'上级分类')
    name = models.CharField(u'名称', max_length=32)
    order = models.IntegerField(u'排序')
    file_id = models.CharField(u'文件ID', max_length=22)

    def __unicode__(self):
        return self.parent.name + '/' + self.name

    class Meta:
        ordering = ['parent', 'order']
        verbose_name = u'条目'
        verbose_name_plural = u'条目'

apps/genuine/views.py
#encoding=utf8
from django.conf import settings
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseServerError
from django.shortcuts import render_to_response, redirect
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

import json
import requests
from uuid import UUID

from libs import oauth_client
from navigation import get_navbar

from .models import Catalog, Item

DATA_ROOT = settings.DATA_ROOT

DREAMSPARK_ACCOUNT = settings.DREAMSPARK_ACCOUNT
DREAMSPARK_KEY = settings.DREAMSPARK_KEY

OPEN_LOGIN_REDIRECT_URI = settings.DREAMSPARK_OPEN_REDIRECT_URI

def index(request):
    result = get_navbar(request)

    return render_to_response('genuine/index.html', result)

def iuv(request):
    if 'action' in request.GET:
        action = request.GET['action']

        if request.GET['action'] == 'signin':
            return oauth_client.login(request, OPEN_LOGIN_REDIRECT_URI, ['get_user_email'])

        elif request.GET['action'] == 'signout':
            return redirect('http://e5.onthehub.com/d.ashx?s=jlg1p270bi')

    if 'code' in request.GET:
        code = request.GET['code']

        if oauth_client.get_token(request, OPEN_LOGIN_REDIRECT_URI, code):
            response = json.loads(oauth_client.get_user_email(request))
            if 'email' not in response:
                return oauth_client.login(request, OPEN_LOGIN_REDIRECT_URI, ['get_user_email'])

            email = response['email']
            oauth_client.logout(request)

            domain = email.split('@')[1]
            if domain.lower() == 'nou.com.cn':
                statuses = 'students'
            elif domain.lower() == 'neusoft.edu.cn':
                statuses = 'faculty,staff'

            payload = {
                'account': DREAMSPARK_ACCOUNT,
                'key': DREAMSPARK_KEY,
                'username': email,
                'academic_statuses': statuses,
                'email': email,
            }

            try:
                r = requests.get('https://e5.onthehub.com/WebStore/Security/AuthenticateUser.aspx', params=payload)
            except requests.exceptions.ConnectionError:
                return HttpResponseServerError('与 DreamSpark 服务器通信超时，请稍后重试。')

            if r.status_code == requests.codes.ok:
                return redirect(r.text)
            else:
                return HttpResponse(r.text)

    if 'error' in request.GET:
        return redirect('http://e5.onthehub.com/d.ashx?s=jlg1p270bi')

    return HttpResponseBadRequest('Bad Request')

def download(request):
    result = get_navbar(request)

    # Catalog > Product > Version > Edition > Item
    product = request.GET.get('product', None)
    if product:
        current = Catalog.objects.get(id=UUID(bytes=urlsafe_base64_decode(product)))
    else:
        current = Catalog.objects.filter(name='Windows')[0] # HARD CODING

    catalogs = []
    for catalog in Catalog.objects.filter(parent=None):
        active = False
        products = []
        for product in catalog.catalog_set.all():
            products.append({'name': product.name, 'id': urlsafe_base64_encode(product.id.bytes)})
            if not active and product == current:
                active = True
        catalogs.append({'name': catalog.name, 'products': products, 'active': active})

    result.update({'catalogs': catalogs})

    versions = []
    for version in current.catalog_set.order_by('-order'):
        editions = []
        for edition in version.catalog_set.all():
            items = []
            for item in edition.item_set.all():
                items.append({'name': item.name, 'file': item.file_id})
            editions.append({'name': edition.name, 'items': items})
        versions.append({'id': version.id, 'name': version.name, 'editions': editions})

    result.update({'versions': versions})

    return render_to_response('genuine/download.html', result)

apps/genuine/templates/genuine/download.html
{% extends "we/base.html" %}
{% load staticfiles %}

{% block title %}下载正版授权软件{% endblock %}

{% block extra_css %}
  <link href="{% static 'genuine/css/we-genuine.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <div class="container">
      <section>
        <div id="navigation" class="panel-group col-md-3">
  {% for catalog in catalogs %}
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title"><a data-toggle="collapse" data-parent="#navigation" href="#catalog{{ forloop.counter }}">{{ catalog.name }}</a></h4>
            </div>
            <div id="catalog{{ forloop.counter }}" class="panel-collapse collapse{% if catalog.active %} in{% endif %}">
              <div class="panel-body">
    {% for product in catalog.products %}
                <a href="?product={{ product.id }}"><i class="glyphicon glyphicon-chevron-right"></i>{{ product.name }}</a><br>
    {% endfor %}
              </div>
            </div>
          </div>
  {% endfor %}
        </div>
        <div class="col-md-9">
  {% for version in versions %}
          <div id="{{ version.id }}" class="page-header">
            <h3>{{ version.name }}</h3>
          </div>
          <table class="table table-hover">
            <thead>
              <tr>
                <th>版本
                <th colspan="4">下载链接
            <tbody>
    {% for edition in version.editions %}
              <tr>
                <td>{{ edition.name|safe }}
      {% for item in edition.items %}
                <td
                {% if edition.items|length == 1 %}
                  colspan="4"
                {% elif edition.items|length == 2 %}
                  colspan="2"
                {% endif %}
                ><a href="{% url 'file:detail' item.file %}">{{ item.name }}</a>
      {% endfor %}
    {% endfor %}
          </table>
  {% endfor %}
        </div>
      </section>
    </div>
{% endblock %}

apps/genuine/templates/genuine/index.html
{% extends "we/hero.html" %}
{% load staticfiles %}

{% block title %}正版授权软件{% endblock %}

{% block extra_css %}
  <link href="{% static 'dreamspark/css/we-dreamspark.css' %}" rel="stylesheet" />
{% endblock %}

{% block hero_title %}We - 正版授权软件{% endblock %}
{% block hero_subtitle %}使用正版授权软件，尽享学习工作乐趣{% endblock %}

{% block content %}
  <div class="container">
    <p class="alert alert-info"><strong>提示：</strong>你可以点击<a href="{% url 'genuine:download' %}"><span class="glyphicon glyphicon-link"></span>这里</a>从校园网高速下载以下全部正版授权软件。
    <section>
      <header class="page-header">
        <h2>微软 DreamSpark 计划</h2>
      </header>
      <p>DreamSpark 是一项 Microsoft 计划，通过允许出于学习、教学和研究的目的来访问 Microsoft 软件，从而为技术教育提供支持。
      <p>我们购买了最高级别的 DreamSpark 计划，学院全体教职员工及具有统招学历的在校学生均可<strong>免费</strong>获得该计划内全部软件的正版授权。
      <header class="page-header">
        <h3>使用方法</h3>
      </header>
      <ol>
        <li>有互联网访问权限的用户，点击<a href="http://e5.onthehub.com/d.ashx?s=jlg1p270bi" target="_blank"><span class="glyphicon glyphicon-new-window"></span>这里</a>访问 DreamSpark 商店（境外服务器，访问速度很慢）；
        <li>点击<strong>「开始购物」</strong>链接后，进入登录页面；
        <li>使用学院开设的邮箱进行登录；
        <li>选择需要的产品，加入购物车进行结算（免费）；
        <li>接受许可协议后，即可获得相应产品的密钥。
      </ol>
    </section>
    <section>
      <header class="page-header">
        <h2>微软批量授权服务</h2>
      </header>
      <p>微软批量授权服务是微软针对企业内部提供的一套操作系统集中授权激活服务，与零售授权不同的是，批量授权仅可在企业内部网络中进行授权激活，当离开企业内部网络后，授权激活将在 180 天内失效。
      <p>我们购买的批量授权服务支持激活的操作系统有 Windows 8.1 、 8 、 7 、 Vista 的企业版及专业版（Vista 商业版）， Windows Server 2012 R2 、 2012 、 2008 R2 、 2008 的所有版本，以及 Office 2010 、 2013 办公套件。
      <header class="page-header">
        <h3>配置方法</h3>
      </header>
      <h4>Windows 激活</h4>
      <ol>
        <li>按键盘上的<code>⊞</code>键，在开始菜单/开始屏幕中输入<code>cmd</code>（注意不要按回车键），稍等片刻，在搜索结果列表的<strong>『命令提示符』</strong>一项上右击，选择<strong>「以管理员身份运行」</strong>；</li>
        <li>在<strong>『命令提示符』</strong>窗口中，输入<code>slmgr /skms kms.we.neusoft.edu.cn&lt;回车&gt;</code>；</li>
        <li>稍等片刻，依次关闭新弹出的窗口及<strong>『命令提示符』</strong>窗口即可。</li>
      </ol>
      <h4>Office 激活</h4>
      <ol>
        <li>首先需要记下你的 Office 安装位置， Office 2013 默认安装位置为<code>C:\Program Files\Microsoft Office\Office15</code>或<code>C:\Program Files (x86)\Microsoft Office\Office15</code>（在 64 位系统中安装 32 位 Office）， Office 2010 默认安装位置为<code>C:\Program Files\Microsoft Office\Office14</code>或<code>C:\Program Files (x86)\Microsoft Office\Office14</code>（在 64 位系统中安装 32 位 Office）；</li>
        <li>按键盘上的<code>⊞</code>键，在开始菜单/开始屏幕中输入<code>cmd</code>（注意不要按回车键），稍等片刻，在搜索结果列表的<strong>『命令提示符』</strong>一项上右击，选择<strong>「以管理员身份运行」</strong>；</li>
        <li>在<strong>『命令提示符』</strong>窗口中，输入<code>cd /d "&lt;安装位置&gt;"&lt;回车&gt;</code>；</li>
        <li>在<strong>『命令提示符』</strong>窗口中，继续输入<code>cscript ospp.vbs /sethst:kms.we.neusoft.edu.cn&lt;回车&gt;</code>；</li>
        <li>稍等片刻，关闭<strong>『命令提示符』</strong>窗口即可。</li>
      </ol>
      <p>经过以上设置之后，将会在接下来一段时间内自动激活相应软件。</p>
    </section>
  </div>
{% endblock %}