apps/mirror/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    (r'^index.we$', views.index),
    url(r'^more.we$', views.MoreView.as_view(), name='more'),
)

we/urls.py
from django.conf.urls import patterns, include

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'we.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    (r'^([^/]+/)?common/', include('common.urls')),
    (r'^www/', include('apps.www.urls', namespace='www')),
    (r'^mirror/', include('apps.mirror.urls', namespace='mirror')),
    (r'^genuine/', include('apps.genuine.urls', namespace='genuine')),
    (r'^file/', include('apps.file.urls', namespace='file')),
    (r'^iptv/', include('apps.iptv.urls', namespace='iptv')),
    (r'^open/', include('apps.open.urls', namespace='open')),

    (r'^me/', include('apps.me.urls', namespace='me')),

    (r'^admin/', include(admin.site.urls)),
)

apps/mirror/models.py
#coding=utf8
from django.db import models

class Mirror(models.Model):
    name = models.CharField(u'镜像名称', max_length=32)
    order = models.IntegerField(u'排序')
    description = models.TextField(u'描述', blank=True)
    active = models.BooleanField(u'活动', default=False)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['order']
        verbose_name = u'镜像'
        verbose_name_plural = u'镜像'

class Status(models.Model):
    mirror = models.OneToOneField(Mirror, verbose_name=u'镜像名称')
    count = models.IntegerField(u'文件总数量', null=True, editable=False)
    size = models.BigIntegerField(u'文件总大小', null=True, editable=False)
    time = models.DateTimeField(u'上次成功同步时间', null=True, editable=False)
    status = models.SmallIntegerField(u'同步状态', null=True, editable=False)

    def __unicode__(self):
        return self.mirror.name

    class Meta:
        ordering = ['mirror']
        verbose_name = u'镜像状态'
        verbose_name_plural = u'镜像状态'

apps/mirror/views.py
#coding=utf-8
from django.shortcuts import render_to_response

from navigation import get_navbar
from converter import file_size

from .models import Mirror, Status
from libs.nav_more import MoreView, get_more_list

pathname = '/storage/mirror/'

# 首页
def index(request):
    result = get_navbar(request)
    result.update({'more_list': get_more_list(request)})

    results = []
    mirrors = Mirror.objects.filter(active=True).order_by('order')
    for mirror in mirrors:
        item = mirror.status

        try:
            if mirror.name in ['cpan']:
                item.status = '实时同步'
                item.style = 'success'
            elif mirror.name in ['kali', 'kali-security']:
                item.status = '被动同步'
                item.style = 'success'
            else:
                if item.status == -1:
                    item.status = '正在同步'
                    item.style = 'info'
                elif item.status == -2:
                    item.status = '正在统计'
                    item.style = 'info'
                elif item.status == 0:
                    item.status = '同步成功'
                    item.style = 'success'
                elif item.status is None:
                    item.status = '状态未知'
                    item.style = 'default'
                else:
                    item.status = '同步失败'
                    item.style = 'danger'

            results.append({
                'mirror': mirror.name, 'status': item.status, 'style': item.style, 'count': item.count, 'size': file_size(item.size), 'timestamp': item.time
            })
        except Status.DoesNotExist:
            pass

    result.update({'results': results})

    return render_to_response('mirror/index.html', result)

class MoreView(MoreView):
    def get_context_data(self, **kwargs):
        context = super(MoreView, self).get_context_data(**kwargs)
        context.update({
            'more_title': '配置说明 - 开源镜像站',
            'more_dropdown': '配置说明',
        })
        return context

apps/mirror/templates/mirror/include/android.html
               <section id="android">
                  <header class="page-header">
                     <h1>Android <small>Android SDK</small></h1>
                  </header>
                  <h2>配置步骤</h2>
                  <ol start="0">
                     <li>启动 Android SDK Manager ，打开主界面，依次选择<strong>「Tools」</strong>、<strong>「Options...」</strong>，弹出<strong>『Android SDK Manager - Settings』</strong>窗口；</li>
                     <li>在<strong>『Android SDK Manager - Settings』</strong>窗口中，在<strong>「HTTP Proxy Server」</strong>和<strong>「HTTP Proxy Port」</strong>输入框内填入<code>mirrors.neusoft.edu.cn</code>和<code>80</code>，并且选中<strong>「Force https://... sources to be fetched using http://...」</strong>复选框。设置完成后单击<strong>「Close」</strong>按钮关闭<strong>『Android SDK Manager - Settings』</strong>窗口返回到主界面；</li>
                     <li>依次选择<strong>「Packages」</strong>、<strong>「Reload」</strong>。
                  </ol>
               </section>

apps/mirror/templates/mirror/include/centos.html
               <section id="centos">
                  <header class="page-header">
                     <h1>CentOS <small>The Community ENTerprise Operation System</small></h1>
                  </header>
                  <p>对于 CentOS 5.x, 6.x, 7.x 版本系统，均可运行下面命令修改系统初始配置文件：
<pre class="prettyprint">
sed -e "s/^mirrorlist/#mirrorlist/g" -e"s/#baseurl/baseurl/g" -e "s/mirror\.centos\.org/mirrors.neusoft.edu.cn/g" -i /etc/yum.repos.d/CentOS-Base.repo
</pre>
                  <p>对于 CentOS 6.x 版本 x86_64 平台系统，还可运行下面命令配置 SCL 仓库：
<pre class="prettyprint">
yum -y install centos-release-SCL
sed -e "s/mirror\.centos\.org/mirrors.neusoft.edu.cn/g" -i /etc/yum.repos.d/CentOS-SCL.repo
</pre>
               </section>

apps/mirror/templates/mirror/include/epel.html
               <section id="epel">
                  <header class="page-header">
                     <h1>EPEL <small>Extra Packages for Enterprise Linux</small></h1>
                  </header>
                  <p>对于没有禁用 extras 仓库的 CentOS 5.x, 6.x, 7.x 版本系统，均可运行下面命令配置 epel 仓库：
<pre class="prettyprint">
yum -y install epel-release
sed -e "s/^mirrorlist/#mirrorlist/g" -e "s/#baseurl/baseurl/g" -e "s/download\.fedoraproject\.org\/pub/mirrors.neusoft.edu.cn/g" -i /etc/yum.repos.d/epel.repo
</pre>
               </section>

apps/mirror/templates/mirror/include/nav_more.html
        <li class="dropdown dropdown-we">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">配置说明&nbsp;<b class="caret"></b></a>
          <ul class="dropdown-menu">
            {% for more in more_list %}
              <li><a href="{% url 'mirror:more' %}#{{ more.key }}">{{ more.title }}</a></li>
            {% endfor %}
          </ul>
        </li>